name: dther
description: Ethereum implementaion in dart
version: 0.0.1
author: kabiir
homepage: https://github.com/kabiir/dther

dependencies:
  pointycastle: "^0.11.1"
  crypto: ">=0.9.2 <3.0.0"
dev_dependencies:
  test: ^0.12.0