name: bieps
description: BIP/EIP implementations in dart
version: 0.0.1
author: kabiir
homepage: https://github.com/kabiir/bieps

dependencies:
  pointycastle: "^0.11.1"
dev_dependencies:
  test: ^0.12.0